### GENERAL SETTINGS ###

# Site settings
title: SGeSports
description: "We are an eSports Organization specializing in the shooter titles Counter-Strike and Valorent."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
netlify_identity: true
baseurl: "" #important: start with /
url: "https://sgesports.club"
logo: "/assets/svgs/logo/sleeping-giants-header.svg"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#1ed49d" #"#F70031"
  primary_rgb: "30,212,157" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#005959" #"#33004D" #2f2f2f
  link: "#00a070"
  link_hover: "#00ad4b"
  footer_heading: "#c3f7e8"
  footer_content: "#c2f6f6"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: fab fa-discord
    url: /discord
  - title: fab fa-twitter
    url: https://twitter.com/SleepingGiantGG
  - title: fab fa-twitch
    url: https://www.twitch.tv/sleepinggiantsesports
  - title: fab fa-steam
    url: https://steamcommunity.com/groups/SGE__
  - title: fab fa-youtube
    url: https://www.youtube.com/channel/UC5GDJCa-5KE5s6bbGGKAkzA
  - title: fas fa-envelope-open-text #use for email address
    url: mailto:sleepinggiantesports@gmail.com

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Join our community on Discord,
    - <a href="https://sgesports.club/discord">https://sgesports.club/discord</a>
    - We hang out, play games, run events,
    - compete for prizes, and other fun stuff. :)
email: sleepinggiantesports@gmail.com
tel: 


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Nolan "Sniper" Paxton
    position: CEO
    text: A pyromaniac.
    img: team01.jpg
    social:
      - title: fab fa-steam-symbol #use for email address
        url: https://steamcommunity.com/profiles/76561198333330178
  - name: Connor "SegFault" Postma
    position: Co-CEO
    text: A big nerd.
    img: team02.jpg
    social:
      - title: fab fa-steam-symbol
        url: https://steamcommunity.com/id/segfaultcs/
      - title: fab fa-twitter
        url: https://twitter.com/segfault_tv
  - name: Stump
    position: COO
    text: team manager, CSGO skin investor.
    img: team03.jpg
    social:
      - title: fab fa-steam-symbol
        url: https://steamcommunity.com/id/stump__/
      - title: fab fa-twitter
        url: https://twitter.com/Stumpy___
  - name: King2k
    position: CCO
    text: Incurable hipster.
    img: team04.jpg
    social:
      - title: fab fa-steam-symbol
        url: https://steamcommunity.com/profiles/76561198145405620

# Clients information. Shown on Home and About pages.
clients:
  - name: example client
    img: client01.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Contrary to our name, the Sleeping Giants never sleep. Bring our game to the next level is our mission, and even in the haze of sleeplessness we destroy competitors who stand in our way. Game on!"

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "The Sleeping Giants community has taught me so much and is lots of fun to be a part of. I am proud to say I get to game along side the talented people of this organization on their off time."
    author: John Smith
    position: happy community member
