backend:
  name: git-gateway
  branch: content-published # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/img/blog" # Media files will be stored in the repo under images/uploads
public_folder: "" # The src attribute for uploaded media will have no directory as it is handled by the theme

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Admin"}
      - {label: "Categories", name: "categories", widget: "list", default: ["blog"]}
      - {label: "Post Image", name: "img", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Videos"
    folder: "_projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Showcase Added Date", name: "date", widget: "datetime"}
      - {label: "Added By", name: "author", widget: "string", default: "Admin"}
      - {label: "Categories", name: "categories", widget: "list", default: ["project"]}
      - {label: "Youtube Video ID", name: "video_id", widget: "string", default: "IEW5zf0tgvc"}
      - {label: "Post Image", name: "img", widget: "image"}
      - {label: "Tags", name: "tagged", widget: "list", default: ["Gaming"]}
      - {label: "Video Creator", name: "creator", widget: "string"}
      - {label: "Short Description", name: "summary", widget: "string"}
      - {label: "Video Description", name: "body", widget: "markdown"}
